export const COMMON_TERMS = {
  pencil: { rc: "athg-fmagl", gloss: "writing tool" },
  pen: { rc: "athg-fmagl", gloss: "writing tool" },
  paper: { rc: "athg-ftaghu", gloss: "writing skin, paper" },
  notebook: { rc: "athg-eeh-ftaghu", gloss: "writing knowledge skin, notebook" },
  desk: { rc: "kthar-ftaghu", gloss: "solid surface, desk" },
  table: { rc: "kthar-ftaghu", gloss: "solid surface, table" },
  chair: { rc: "bthnk-fhtagn-fmagl", gloss: "body-resting tool, chair" },
  door: { rc: "nglui-hu", gloss: "gate skin, door" },
  window: { rc: "yll-nglui", gloss: "light gate, window" },
  room: { rc: "wgah'nagl-vren", gloss: "small dwelling-place, room" },
  house: { rc: "wgah'nagl", gloss: "dwelling-place, house" },
  home: { rc: "y-wgah'nagl", gloss: "one's dwelling-place, home" },
  school: { rc: "kadishtu-agl", gloss: "knowledge place, school" },
  teacher: { rc: "kadishtu-fhayak-nyth", gloss: "knowledge-giving practitioner, teacher" },
  student: { rc: "kadishtu-ilyaa-nyth", gloss: "knowledge-seeking practitioner, student" },
  child: { rc: "gof'nn-vren", gloss: "small offspring, child" },
  parent: { rc: "gof'nn-hup-yth", gloss: "source of offspring, parent" },
  mother: { rc: "gof'nn-hup-yth", gloss: "offspring-source, mother" },
  father: { rc: "ygnaiih", gloss: "father" },
  friend: { rc: "vra-ctenff-yth", gloss: "with-community person, friend" },
  person: { rc: "shuggoth", gloss: "earth-native person" },
  people: { rc: "shuggoth-rii", gloss: "people" },
  food: { rc: "bthnk-uln", gloss: "body-summoned sustenance, food" },
  bread: { rc: "shugg-kthar-vren", gloss: "earth-solid small food, bread" },
  rice: { rc: "shugg-vren-ri", gloss: "many small earth grains, rice" },
  fruit: { rc: "rhygg-gof'nn", gloss: "plant offspring, fruit" },
  water: { rc: "ulh", gloss: "water" },
  tea: { rc: "rhygg-ulh", gloss: "plant water, tea" },
  coffee: { rc: "n'ghft-rhygg-ulh", gloss: "dark plant water, coffee" },
  cup: { rc: "ulh-ftaghu", gloss: "liquid skin, cup" },
  bottle: { rc: "ulh-wgah'n", gloss: "liquid dwelling, bottle" },
  bag: { rc: "ftaghu-wgah'n", gloss: "skin container, bag" },
  box: { rc: "kthar-wgah'n", gloss: "solid container, box" },
  key: { rc: "nglui-fmagl", gloss: "gate tool, key" },
  phone: { rc: "ghor-ai-fmagl", gloss: "sound-calling tool, phone" },
  computer: { rc: "phlegeth-lloig'agl", gloss: "information mind-place, computer" },
  internet: { rc: "nilgh'ri-phlegeth-uln'agl", gloss: "all-information summoning place, internet" },
  screen: { rc: "yll-ftaghu", gloss: "light surface, screen" },
  keyboard: { rc: "athg-zhrn-fmagl", gloss: "ordered writing tool, keyboard" },
  mouse: { rc: "yll-bug-fmagl", gloss: "light-moving tool, mouse" },
  camera: { rc: "yll-mnahn-fmagl", gloss: "light-memory tool, camera" },
  umbrella: { rc: "ulh-ftaghu-fmagl", gloss: "water-cover tool, umbrella" },
  car: { rc: "bug-fmagl", gloss: "travel tool, car" },
  bus: { rc: "ghrath-bug-fmagl", gloss: "large travel tool, bus" },
  train: { rc: "zhrn-bug-fmagl", gloss: "ordered travel tool, train" },
  bicycle: { rc: "ghal-zhrn-bug-fmagl", gloss: "two-cycle travel tool, bicycle" },
  road: { rc: "bug-agl", gloss: "travel place, road" },
  street: { rc: "wgah'nagl-bug'agl", gloss: "city travel place, street" },
  map: { rc: "bug-eeh-ftaghu", gloss: "travel knowledge skin, map" },
  money: { rc: "k'yarnak-zhrn", gloss: "exchange number/order, money" },
  price: { rc: "k'yarnak-zhrn-eeh", gloss: "exchange-number answer, price" },
  store: { rc: "k'yarnak-wgah'nagl", gloss: "exchange dwelling-place, store" },
  market: { rc: "k'yarnak-ctenff'agl", gloss: "exchange community place, market" },
  work: { rc: "ah-na", gloss: "work, action-state" },
  job: { rc: "ah-s'uhn", gloss: "work pact, job" },
  office: { rc: "ah-wgah'nagl", gloss: "work dwelling-place, office" },
  hospital: { rc: "bthnk-kadishtu-wgah'nagl", gloss: "body-knowledge dwelling-place, hospital" },
  medicine: { rc: "bthnk-wk'hmr-fmagl", gloss: "body-transforming tool, medicine" },
  doctor: { rc: "bthnk-kadishtu-nyth", gloss: "body-knowledge practitioner, doctor" },
  book: { rc: "eeh-ftaghu", gloss: "knowledge skin, book" },
  story: { rc: "mnahn-ai", gloss: "memory speech, story" },
  word: { rc: "ai-ftaghu", gloss: "speech skin, word" },
  language: { rc: "ai-zhrn-ri", gloss: "speech-order totality, language" },
  music: { rc: "ghor-zhrn", gloss: "ordered sound, music" },
  song: { rc: "ghor-ai", gloss: "sound speech, song" },
  image: { rc: "yll-mnahn", gloss: "light memory, image" },
  picture: { rc: "yll-mnahn", gloss: "light memory, picture" },
  color: { rc: "yll-hu", gloss: "light skin, color" },
  red: { rc: "mghal-yll", gloss: "blood light, red" },
  black: { rc: "n'ghft-yll", gloss: "dark light, black" },
  white: { rc: "yll-ri", gloss: "all-light, white" },
  blue: { rc: "ulh-yll", gloss: "water light, blue" },
  green: { rc: "rhygg-yll", gloss: "plant light, green" },
  day: { rc: "yll-rhan", gloss: "light time, day" },
  night: { rc: "n'ghft-rhan", gloss: "dark time, night" },
  week: { rc: "zhral-rhan-ri", gloss: "seven-time totality, week" },
  year: { rc: "ghrath-rhan", gloss: "great cycle, year" },
  time: { rc: "rhan", gloss: "time, cycle" },
  question: { rc: "kn'a", gloss: "question" },
  answer: { rc: "eeh", gloss: "answer" },
  problem: { rc: "kn'a-s'uhn", gloss: "question-bound problem" },
  idea: { rc: "lloig-eeh", gloss: "mind-answer, idea" },
  plan: { rc: "zhrn-ilyaa-eeh", gloss: "ordered expected knowledge, plan" },
  name: { rc: "ai-hu", gloss: "calling skin, name" },
  family: { rc: "gof'nn-ctenff", gloss: "offspring community, family" },
  city: { rc: "wgah'nagl-ri", gloss: "dwelling-place totality, city" },
  country: { rc: "shugg-ctenff-ri", gloss: "earth community totality, country" },
  world: { rc: "shugg-ri", gloss: "earth totality, world" }
};
